
import React from 'react';

// Conteúdo do CSV do Google Sheets (ID: 1Fh8G2vQ1Tu4_qXghW6q5X2noxvUAuJA0m70pAwxka-s)
// Os dados foram embutidos diretamente no componente para exibição em texto.
const csvData = [
    {
        "Coluna 1": "11/12/2025 12:36:25",
        "Coluna 2": "cristianosilva.ufsc@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "CRISTIANO MARIANO",
        "Coluna 5": "10964655555",
        "Coluna 6": "48966665555",
        "Coluna 7": "5555555",
        "Coluna 8": "https://drive.google.com/open?id=1JfZCsLoXg3klxXGNeZabLQvxI_aP8ZDJ",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "EVENTO TESTE",
        "Coluna 31": "Música",
        "Coluna 32": "Apresentação",
        "Coluna 33": "TESTE",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "TESTANDO",
        "Coluna 39": "NÃO",
        "Coluna 40": "",
        "Coluna 41": "SIM",
        "Coluna 42": "Projeto 12:30",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 12:39:07",
        "Coluna 2": "cristianosilva.ufsc@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "MARIANO",
        "Coluna 5": "55555555555",
        "Coluna 6": "555555555555",
        "Coluna 7": "555555555555",
        "Coluna 8": "https://drive.google.com/open?id=1VFQjLV_p0rJPeAdpd84EBA62FIrfMydi",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "TESTE",
        "Coluna 31": "Música",
        "Coluna 32": "Apresentação",
        "Coluna 33": "TESTANDO",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "NÃO",
        "Coluna 40": "",
        "Coluna 41": "SIM",
        "Coluna 42": "Projeto 12:30",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 12:49:05",
        "Coluna 2": "cristianosilva.ufsc@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "CRIS",
        "Coluna 5": "555555555",
        "Coluna 6": "555555555555",
        "Coluna 7": "5555555555",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "TESTE",
        "Coluna 31": "Teatro",
        "Coluna 32": "Apresentação",
        "Coluna 33": "TESTE",
        "Coluna 34": "",
        "Coluna 35": "TESTE",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "TESTE",
        "Coluna 39": "NÃO",
        "Coluna 40": "",
        "Coluna 41": "SIM",
        "Coluna 42": "Projeto 12:30",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 12:55:48",
        "Coluna 2": "cristianosilva.ufsc@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "",
        "Coluna 5": "55555555",
        "Coluna 6": "5555555555",
        "Coluna 7": "",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "5555555555",
        "Coluna 31": "Teatro",
        "Coluna 32": "Apresentação",
        "Coluna 33": "",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "",
        "Coluna 40": "",
        "Coluna 41": "SIM",
        "Coluna 42": "",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 15:00:37",
        "Coluna 2": "hh@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "hhhhhhhhhhhhh",
        "Coluna 5": "hhhhhhhhhhhhh",
        "Coluna 6": "hhhhhhhhhh",
        "Coluna 7": "hhhhhhhhhhhhhhh",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "hhhhhhhhhhhhh",
        "Coluna 31": "Teatro",
        "Coluna 32": "Apresentação",
        "Coluna 33": "hhhhhhhhhhhhhhh",
        "Coluna 34": "",
        "Coluna 35": "hhhhhhhhhhhh",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "hhhhhhhhhhhh",
        "Coluna 39": "NÃO",
        "Coluna 40": "",
        "Coluna 41": "SIM",
        "Coluna 42": "Projeto 12:30",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 15:11:39",
        "Coluna 2": "fgf@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "ggg",
        "Coluna 5": "ggg",
        "Coluna 6": "gggg",
        "Coluna 7": "ggg",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "gggg",
        "Coluna 31": "Teatro",
        "Coluna 32": "Apresentação",
        "Coluna 33": "gggg",
        "Coluna 34": "",
        "Coluna 35": "gggg",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "ggg",
        "Coluna 39": "SIM",
        "Coluna 40": "Legendas",
        "Coluna 41": "SIM",
        "Coluna 42": "Não, pretendo fazer com produção própria.",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 15:38:01",
        "Coluna 2": "lll@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "lllllllllllll",
        "Coluna 5": "llllllllllllll",
        "Coluna 6": "llllllllllllllll",
        "Coluna 7": "lllllllllllllll",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "lllllllllllll",
        "Coluna 31": "Teatro",
        "Coluna 32": "Apresentação",
        "Coluna 33": "llllllllllll",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "",
        "Coluna 40": "",
        "Coluna 41": "",
        "Coluna 42": "",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 16:02:36",
        "Coluna 2": "ygy@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "ddddddddddddddddd",
        "Coluna 5": "ddddddddddddddddd",
        "Coluna 6": "ddddddddddddddddddddd",
        "Coluna 7": "dddddddddddddddddd",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "",
        "Coluna 31": "",
        "Coluna 32": "",
        "Coluna 33": "",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "",
        "Coluna 40": "",
        "Coluna 41": "",
        "Coluna 42": "",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 23:18:57",
        "Coluna 2": "gvg@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "",
        "Coluna 5": "",
        "Coluna 6": "",
        "Coluna 7": "",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "",
        "Coluna 31": "Audiovisual",
        "Coluna 32": "Gravação",
        "Coluna 33": "",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "",
        "Coluna 40": "",
        "Coluna 41": "SIM",
        "Coluna 42": "Projeto 12:30",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "11/12/2025 23:22:10",
        "Coluna 2": "kjlnh@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "",
        "Coluna 5": "",
        "Coluna 6": "",
        "Coluna 7": "",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "",
        "Coluna 31": "",
        "Coluna 32": "",
        "Coluna 33": "",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "",
        "Coluna 40": "",
        "Coluna 41": "",
        "Coluna 42": "",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "12/12/2025 10:16:41",
        "Coluna 2": "testecris.0001@gmail.com",
        "Coluna 3": "Pessoa Física",
        "Coluna 4": "",
        "Coluna 5": "",
        "Coluna 6": "5555555555",
        "Coluna 7": "55555555555555",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "NÃO",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "5555555555555555",
        "Coluna 31": "Teatro",
        "Coluna 32": "",
        "Coluna 33": "",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "NÃO",
        "Coluna 40": "",
        "Coluna 41": "SIM",
        "Coluna 42": "Projeto 12:30",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "09/12/2025, 22:23:42",
        "Coluna 2": "yg",
        "Coluna 3": "hghg@gmail.com",
        "Coluna 4": "cx",
        "Coluna 5": "PLANILHA",
        "Coluna 6": "teatro",
        "Coluna 7": "",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "[{'inicio':'2026-01-02T08:00:00','fim':'2026-01-02T08:30:00','eventId':'dj0usr156jisidn9vmk2r10c2o'}]",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "",
        "Coluna 31": "",
        "Coluna 32": "",
        "Coluna 33": "",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "",
        "Coluna 40": "",
        "Coluna 41": "",
        "Coluna 42": "",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "09/12/2025, 22:35:30",
        "Coluna 2": "uyihu",
        "Coluna 3": "uhu@gmail.com",
        "Coluna 4": "ioji",
        "Coluna 5": "klkjk",
        "Coluna 6": "teatro",
        "Coluna 7": "",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "[{'inicio':'2026-01-03T08:00:00','fim':'2026-01-03T09:30:00','eventId':'61g3dt0euupfv6gmdg1adajj58'}]",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "",
        "Coluna 31": "",
        "Coluna 32": "",
        "Coluna 33": "",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "",
        "Coluna 40": "",
        "Coluna 41": "",
        "Coluna 42": "",
        "Coluna 43": ""
    },
    {
        "Coluna 1": "09/12/2025, 23:32:44",
        "Coluna 2": "hv",
        "Coluna 3": "vhv@gmail.com",
        "Coluna 4": "bh",
        "Coluna 5": "AAAHH",
        "Coluna 6": "teatro",
        "Coluna 7": "",
        "Coluna 8": "",
        "Coluna 9": "",
        "Coluna 10": "",
        "Coluna 11": "",
        "Coluna 12": "",
        "Coluna 13": "[{'inicio':'2026-01-01T09:00:00','fim':'2026-01-01T09:30:00','eventId':'rvjs8tjobsbt3oik8sds0laom0'}]",
        "Coluna 14": "",
        "Coluna 15": "",
        "Coluna 16": "",
        "Coluna 17": "",
        "Coluna 18": "",
        "Coluna 19": "",
        "Coluna 20": "",
        "Coluna 21": "",
        "Coluna 22": "",
        "Coluna 23": "",
        "Coluna 24": "",
        "Coluna 25": "",
        "Coluna 26": "",
        "Coluna 27": "",
        "Coluna 28": "",
        "Coluna 29": "",
        "Coluna 30": "",
        "Coluna 31": "",
        "Coluna 32": "",
        "Coluna 33": "",
        "Coluna 34": "",
        "Coluna 35": "",
        "Coluna 36": "",
        "Coluna 37": "",
        "Coluna 38": "",
        "Coluna 39": "",
        "Coluna 40": "",
        "Coluna 41": "",
        "Coluna 42": "",
        "Coluna 43": ""
    }
];

const Pagina = () => {
  return (
    <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif', maxWidth: '1200px', margin: '0 auto' }}>
      <h1 style={{ borderBottom: '2px solid #eee', paddingBottom: '10px' }}>
        Dados do Google Sheets (CSV)
      </h1>
      <p style={{ marginBottom: '20px', color: '#555' }}>
        Total de Registros Encontrados: <strong>{csvData.length}</strong>
      </p>
      
      {csvData.map((row, rowIndex) => (
        <div 
          key={rowIndex} 
          style={{ 
            border: '1px solid #ccc', 
            borderRadius: '8px', 
            margin: '15px 0', 
            padding: '15px', 
            backgroundColor: rowIndex % 2 === 0 ? '#f9f9f9' : '#fff' 
          }}
        >
          <h2 style={{ marginTop: '0', fontSize: '1.2em', color: '#333' }}>
            Registro #{rowIndex + 1}
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '10px' }}>
            {Object.entries(row).map(([key, value]) => (
              <p key={key} style={{ margin: '5px 0', wordBreak: 'break-word' }}>
                <strong style={{ color: '#000' }}>{key}:</strong> {value || 'N/A'}
              </p>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
};

export default Pagina;
